title: Public Affairs Data Journalism at Stanford; Fall 2016
description: |
  1s and 0s
authors:
  - Dan Nguyen
image_url: /assets/images/logo.png
baseurl: "https://2016.padjo.org"


services:
  google_analytics:
    id: UA-55019978-1
