DELETE FROM indiv
WHERE CMTE_ID IN (
    SELECT CAND_PCC
    FROM cn
    WHERE
        CAND_PCC IS NOT NULL
        AND (CAND_OFFICE = 'P' OR CAND_OFFICE_ST != 'CA')
)


DELETE FROM oppexp
WHERE CMTE_ID IN (
    SELECT CAND_PCC
    FROM cn
    WHERE
        CAND_PCC IS NOT NULL
        AND (CAND_OFFICE = 'P' OR CAND_OFFICE_ST != 'CA')
)

DELETE FROM pas2
WHERE CMTE_ID IN (
    SELECT CAND_PCC
    FROM cn
    WHERE
        CAND_PCC IS NOT NULL
        AND (CAND_OFFICE = 'P' OR CAND_OFFICE_ST != 'CA')
)


